trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Deploy
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'TestConnection'
        subscriptionId: '6ca07c31-0732-408a-8b17-075fb6998548'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'myResourceGroup'
        location: 'Canada Central'
        templateLocation: 'Linked artifact'
        csmFile: 'main.bicep'
        csmParametersFile: 'parameters.json'
        deploymentMode: 'Incremental'
        
        
        
        
        
        
