trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'TestConnection'
    subscriptionId: '6ca07c31-0732-408a-8b17-075fb6998548'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg'
    location: 'Brazil US'
    templateLocation: 'Linked artifact'
    csmFile: 'main.bicep'
    csmParametersFile: 'parameter.json'
    deploymentMode: 'Incremental'